apiVersion: v1
kind: Secret
metadata:
  name: secret-basic-auth
  namespace: {{ .Values.namespace }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.postgres.user }}
  password: {{ .Values.secret.password }}
