apiVersion: v1
kind: Secret
metadata:
  namespace: todo-app
  name: secret-basic-auth
type: kubernetes.io/basic-auth
stringData:
  username: postgres # required field for kubernetes.io/basic-auth
  password: password # required field for kubernetes.io/basic-auth