namespace: todo-app

frontend:
  image:
    repository: digdigdigdig/manualproject-frontend
    tag: d88aa3371051712fca217a62c7d2b2b3f5bf73ab
  replicas: 1
  port: 80

backend:
  image:
    repository: digdigdigdig/manualproject-backend
    tag: d88aa3371051712fca217a62c7d2b2b3f5bf73ab
  replicas: 1
  port: 5000

postgres:
  image:
    repository: postgres
    tag: 15
  replicas: 1
  port: 5432
  database: todos
  user: postgres

secret:
  password: password

ingress:
  className: nginx
  frontendPath: /
  backendPath: /tasks

rbac:
  devUser: dev-user
  adminUser: admin-user

backup:
  serviceAccount:
    name: backup-service-account
    roleArn: arn:aws:iam::444062204470:role/todo-app-s3-backup-role
